### ISSUE TITLE
May cause crash

### ISSUE THREAD

**Issue by narsu1984** [spin6lock/python-sproto#10]
![1](https://cloud.githubusercontent.com/assets/3960661/14487245/28640f6e-0194-11e6-98e7-054c22cb7d9f.png)
![2](https://cloud.githubusercontent.com/assets/3960661/14487253/34594d70-0194-11e6-97e5-078b928bb197.png)
图1出现了两次异常,都是由c++层在不同帧调用的,逻辑上并没有直接关系.
但进行图2的修改后,第二个异常就不会再出现.

**Comment by narsu1984** [comment]
![3](https://cloud.githubusercontent.com/assets/3960661/14488690/020e86fc-019c-11e6-97d7-949758951913.png)
从调用堆栈看,是在gc 的 collect 出现的异常.
你们平时用python会disable gc么?

**Comment by spin6lock** [comment]
没有disable gc来用，不过我们是用来写自动化测试用的，所以可能生命周期很短，没有把问题暴露出来，我明天看看哈~

**Comment by spin6lock** [comment]
用PyObject_Del直接删除的确不妥，我改了，麻烦看一下:laughing:

**Comment by narsu1984** [comment]
应该可以了, thank you
