### ISSUE TITLE
vs2012编译不通过

### ISSUE THREAD

**Issue by lpyvvvvvv** [spin6lock/python-sproto#11]
我在vs2012里用静态库的方式编译python-sproto，但是编译出错，我的python版本是2.7.8。
下面是错误信息，我并没有修改源代码。请问是什么问题？
1>c:\users\documents\visual studio 2012\projects\testsproto\pysproto\python_sproto.c(103): error C2143: 语法错误 : 缺少“;”(在“类型”的前面)
1>c:\users\documents\visual studio 2012\projects\testsproto\pysproto\python_sproto.c(104): error C2275: “Py_ssize_t”: 将此类型用作表达式非法
1>          c:\users\documents\visual studio 2012\projects\testsproto\pythonlib\include\pyport.h(183) : 参见“Py_ssize_t”的声明
1>c:\users\documents\visual studio 2012\projects\testsproto\pysproto\python_sproto.c(104): error C2146: 语法错误: 缺少“;”(在标识符“len”的前面)
1>c:\users\documents\visual studio 2012\projects\testsproto\pysproto\python_sproto.c(104): error C2065: “len”: 未声明的标识符
1>c:\users\documents\visual studio 2012\projects\testsproto\pysproto\python_sproto.c(105): error C2065: “string_ptr”: 未声明的标识符

**Comment by lpyvvvvvv** [comment]
把.c文件改成.cpp文件，然后加上类型转换就通过编译了。。。。

**Comment by spin6lock** [comment]
感谢反馈
