### ISSUE TITLE
嵌套类型，跳过嵌套的第一个字段，无法通过测试

### ISSUE THREAD

**Issue by mayao11** [spin6lock/python-sproto#12]
修改test.py的test_complex_encode_decode 函数，跳过d.world.a，测试不通过

    def test_complex_encode_decode(self):
       .............
        source = { 
            "a" : "hello",
            "b" : 1000000,
            "c" : True,
            "d" : { 
                "world":{
                        #skip a 
                        #"a" : "world", 
                        #skip b
                        "c" : -1, 
                    },  
                "two":{
        .................

**Comment by spin6lock** [comment]
...数据不一样了当然不通过啊

**Comment by mayao11** [comment]
我意思是encode任意数据时，如果嵌套字段的第一个成员没有给出，encode时会失败。

**Comment by spin6lock** [comment]
@mayao11 这里skip掉a有问题，是因为d对应的是*nest(a)，以a为index的，没有a的话解包重建dict的时候，会缺少key。要不你另外给个例子？

**Comment by mayao11** [comment]
明白了，这个严格来说算一个缺陷吧。
如果没有辅助字段，还真重建不出来。protobuf应该是通过附加是否为空的标记来做的？

**Comment by spin6lock** [comment]
@mayao11 不太清楚protobuf的情况，我用protobuf的时候还是protobuf2，没有字典支持。其实这个特性算是一个扩展吧，就是你知道这个数组最后会用元素的某个字段作为key，然后让sproto帮你做了，不定义*nest(a)里面的a是不会有问题的

**Comment by mayao11** [comment]
原来nest(a)是这个意思啊。。。好费解，明白了。是我没看懂定义
