### ISSUE TITLE
map的key是int的时候，解析不了内容

### ISSUE THREAD

**Issue by HappyMiluo** [spin6lock/python-sproto#17]
如题，如果有一个map的key是int的时候，解析会有问题

**Comment by HappyMiluo** [comment]
.heroinfo {
	id 0 : integer
	lv 1 : integer
	cfgid 2 : integer
}

synbuildinfo 1	{
	request {
		herolist 0 : *heroinfo(id)
	}
}

大概这样一条协议结构，做为key的id是数值型，解析出来的结构，打印出来  是一个[]这样的

**Comment by spin6lock** [comment]
@HappyMiluo 应该是我判断索引的时候写错了，用索引为0的key组成字典就会出错。。。修复了
