### ISSUE TITLE
windows编译环境的疑问

### ISSUE THREAD

**Issue by BigWay2018** [spin6lock/python-sproto#18]
编译环境是windows7 64位、python2.7.3、mingw编译的，有几条用例不能通过，比如下图
![default](https://user-images.githubusercontent.com/29256416/41808301-f1c23890-770d-11e8-9cc8-f5562efc3224.png)

linux下是没问题的，想了解一下windows要怎么编译使用比较好，谢谢

**Comment by spin6lock** [comment]
抱歉，不太熟悉Windows编译，看起来是某个整数类型跟预期的不一致，发生了回绕，我等下再看看。。

**Comment by spin6lock** [comment]
@BigWay2018 配了一下午都没把环境搞出来。。。你看看[encode](https://github.com/spin6lock/python-sproto/blob/4193b6fb17b6a3bd2aaa70d428d58acc41ca630d/python_sproto.c#L80)和[decode](https://github.com/spin6lock/python-sproto/blob/4193b6fb17b6a3bd2aaa70d428d58acc41ca630d/python_sproto.c#L214)的这两个判断有没有走对？应该都走8，即64位的

**Comment by BigWay2018** [comment]
@spin6lock 参考了https://github.com/spin6lock/python-sproto/issues/7  将data = Py_BuildValue("l", *(int64_t*)i);   改为data = Py_BuildValue("L", *(int64_t*)i);解决了图中的问题，，encode和decode都没问题。
![default](https://user-images.githubusercontent.com/29256416/41903857-8cb82028-7969-11e8-84c8-091787ce9802.png)
然后发现现在主要的问题似乎是在运行sproto_protocol时会挂掉，也看不到报错。

**Comment by spin6lock** [comment]
@BigWay2018 非常感谢，我先修一下long long的问题，sproto_protocol新建一个issue弄一下
