### ISSUE TITLE
请问下参数说明

### ISSUE THREAD

**Issue by whaoinfo** [spin6lock/python-sproto#20]
with open('your.spb', 'r') as fh:
    content = fh.read()
  sproto_obj = SprotoRpc(content, content, base_package) #base_package is your package struct name
  p = sproto_obj.request('client.hello', {'foo':'bar'})
  sock.send(p)

请问下这个base_package 参数具体是指的什么呢？

**Comment by spin6lock** [comment]
@whaoinfo 以前在业务包外会包一层，加些通用信息比如包的序号等等，跟包的具体业务内容无关的信息。。
