### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ffbh123456** [spin6lock/python-sproto#23]
mac下python 3.8.2
py3_test 分支

(venv) ➜  sproto git:(master) ✗ python setup.py build
running build
running build_ext
building 'pysproto' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/Users/jiazhi.zhou/Software/BEMIT/venv/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c python_sproto.c -o build/temp.macosx-10.14.6-x86_64-3.8/python_sproto.o
python_sproto.c:55:46: error: implicit declaration of function 'PyString_FromFormat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                PyErr_SetObject(SprotoError, PyString_FromFormat("Expected List or Dict for tagname:%s", tagname));
                                             ^
python_sproto.c:55:46: note: did you mean 'PyBytes_FromFormat'?
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/bytesobject.h:56:24: note: 'PyBytes_FromFormat' declared here
PyAPI_FUNC(PyObject *) PyBytes_FromFormat(const char*, ...)
                       ^
python_sproto.c:55:46: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'PyObject *' (aka 'struct _object *') [-Wint-conversion]
                PyErr_SetObject(SprotoError, PyString_FromFormat("Expected List or Dict for tagname:%s", tagname));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/pyerrors.h:10:56: note: passing argument to parameter here
PyAPI_FUNC(void) PyErr_SetObject(PyObject *, PyObject *);
                                                       ^
python_sproto.c:70:17: error: implicit declaration of function 'PyInt_Check' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            if (PyInt_Check(data) || PyLong_Check(data) || ((args->extra) && PyFloat_Check(data))) {
                ^
python_sproto.c:88:46: error: implicit declaration of function 'PyString_FromFormat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                PyErr_SetObject(SprotoError, PyString_FromFormat("type mismatch, tag:%s, expected int or long", tagname));
                                             ^
python_sproto.c:88:46: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'PyObject *' (aka 'struct _object *') [-Wint-conversion]
                PyErr_SetObject(SprotoError, PyString_FromFormat("type mismatch, tag:%s, expected int or long", tagname));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/pyerrors.h:10:56: note: passing argument to parameter here
PyAPI_FUNC(void) PyErr_SetObject(PyObject *, PyObject *);
                                                       ^
python_sproto.c:107:22: error: implicit declaration of function 'PyString_Check' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (!PyString_Check(data)) {
                     ^
python_sproto.c:107:22: note: did you mean 'PyMapping_Check'?
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/abstract.h:756:17: note: 'PyMapping_Check' declared here
PyAPI_FUNC(int) PyMapping_Check(PyObject *o);
                ^
python_sproto.c:108:50: error: implicit declaration of function 'PyString_FromFormat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    PyErr_SetObject(SprotoError, PyString_FromFormat("type mismatch, tag:%s, expected string", tagname));
                                                 ^
python_sproto.c:108:50: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'PyObject *' (aka 'struct _object *') [-Wint-conversion]
                    PyErr_SetObject(SprotoError, PyString_FromFormat("type mismatch, tag:%s, expected string", tagname));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/pyerrors.h:10:56: note: passing argument to parameter here
PyAPI_FUNC(void) PyErr_SetObject(PyObject *, PyObject *);
                                                       ^
python_sproto.c:111:17: error: implicit declaration of function 'PyString_AsStringAndSize' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                PyString_AsStringAndSize(data, &string_ptr, &len);
                ^
python_sproto.c:111:17: note: did you mean 'PyBytes_AsStringAndSize'?
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/bytesobject.h:103:17: note: 'PyBytes_AsStringAndSize' declared here
PyAPI_FUNC(int) PyBytes_AsStringAndSize(
                ^
python_sproto.c:114:50: error: implicit declaration of function 'PyString_FromFormat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    PyErr_SetObject(SprotoError, PyString_FromFormat("type mismatch, tag:%s, expected unicode", tagname));
                                                 ^
python_sproto.c:114:50: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'PyObject *' (aka 'struct _object *') [-Wint-conversion]
                    PyErr_SetObject(SprotoError, PyString_FromFormat("type mismatch, tag:%s, expected unicode", tagname));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/pyerrors.h:10:56: note: passing argument to parameter here
PyAPI_FUNC(void) PyErr_SetObject(PyObject *, PyObject *);
                                                       ^
python_sproto.c:118:17: error: implicit declaration of function 'PyString_AsStringAndSize' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                PyString_AsStringAndSize(tmp_str, &string_ptr, &len);
                ^
python_sproto.c:404:42: error: implicit declaration of function 'PyString_FromFormat' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            PyErr_SetObject(SprotoError, PyString_FromFormat("out of memory"));
                                         ^
python_sproto.c:404:42: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'PyObject *' (aka 'struct _object *') [-Wint-conversion]
            PyErr_SetObject(SprotoError, PyString_FromFormat("out of memory"));
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/pyerrors.h:10:56: note: passing argument to parameter here
PyAPI_FUNC(void) PyErr_SetObject(PyObject *, PyObject *);
                                                       ^
python_sproto.c:431:9: error: implicit declaration of function 'PyInt_Check' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (PyInt_Check(name_or_tagid)) {
        ^
python_sproto.c:432:17: error: implicit declaration of function 'PyInt_AsLong' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        tagid = PyInt_AsLong(name_or_tagid);
                ^
python_sproto.c:432:17: note: did you mean 'PyLong_AsLong'?
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/longobject.h:23:18: note: 'PyLong_AsLong' declared here
PyAPI_FUNC(long) PyLong_AsLong(PyObject *);
                 ^
python_sproto.c:439:16: error: implicit declaration of function 'PyString_AsString' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        name = PyString_AsString(name_or_tagid);
               ^
python_sproto.c:439:14: warning: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
        name = PyString_AsString(name_or_tagid);
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
python_sproto.c:496:9: error: implicit declaration of function 'Py_InitModule' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    m = Py_InitModule("pysproto", pysproto_methods);
        ^
python_sproto.c:496:7: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
    m = Py_InitModule("pysproto", pysproto_methods);
      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
python_sproto.c:498:9: error: non-void function 'initpysproto' should return a value [-Wreturn-type]
        return;
        ^
7 warnings and 14 errors generated.
error: command 'clang' failed with exit status 1

**Comment by spin6lock** [comment]
@ZhouJiaZhi 看起来是头文件没找到，Mac下的路径可能不一样，请问最后解决了吗？

**Comment by ffbh123456** [comment]
@spin6lock 
头文件是有问题，不过这个报错是我把分支弄错了，我使用的是master分支，我改成py3test分支编译成功了
