### ISSUE TITLE
basestring是什么

### ISSUE THREAD

**Issue by ffbh123456** [spin6lock/python-sproto#24]
如下图
![image](https://user-images.githubusercontent.com/20750357/102712647-bd003a80-42fd-11eb-8a67-dfc4d8fc6764.png)

**Comment by spin6lock** [comment]
> 如下图
> ![image](https://user-images.githubusercontent.com/20750357/102712647-bd003a80-42fd-11eb-8a67-dfc4d8fc6764.png)

https://www.runoob.com/python/python-func-basestring.html

**Comment by ffbh123456** [comment]
这是py2的？py3貌似没有
