### ISSUE TITLE
使用binary类型的字段会报错

### ISSUE THREAD

**Issue by ffbh123456** [spin6lock/python-sproto#29]
看报错好像是sproto.decode的时候把binary当做utf-8的string了？

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte
The above exception was the direct cause of the following exception:

**Comment by ffbh123456** [comment]
分支是py3_test

**Comment by spin6lock** [comment]
看着像是https://github.com/spin6lock/python-sproto/blob/2ea7948a6ac9c04983f4fefe0f732516833440d2/python_sproto.c#L233 这一行，我看文档：https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue 的确是用utf8来构建string的，是不是这里我返回一个bytes数组比较合理？

**Comment by ffbh123456** [comment]
是的，我把s#改成了y#好像就可以了

**Comment by ffbh123456** [comment]
sproto_encode可能也有问题，不过我没有测试过

**Comment by spin6lock** [comment]
@ZhouJiaZhi 非常感谢！修复了一版，可以更新py3_test分支后再试

**Comment by ffbh123456** [comment]
测了下没有发现问题，感谢
