### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by narsu1984** [spin6lock/python-sproto#3]
系统:window7 64位
python:2.7.9 64位
有3处会引起内存泄漏.
如图:
![1](https://cloud.githubusercontent.com/assets/3960661/10557318/a793b0ac-74d9-11e5-8b99-93c76ab4c7b6.png)
![2](https://cloud.githubusercontent.com/assets/3960661/10557319/a794d84c-74d9-11e5-87f4-bdc6f4969bce.png)
![3](https://cloud.githubusercontent.com/assets/3960661/10557317/a78a5ef8-74d9-11e5-84d7-9e407ebab442.png)

**Comment by spin6lock** [comment]
@narsu1984 感谢指正，我明天修复^_^

**Comment by narsu1984** [comment]
非常感谢@spin6lock 对sproto的贡献 :-)
我们项目引用了python-sproto,非常便捷.
上述问题是测试发现的,修复是否严禁还需验证.

**Comment by narsu1984** [comment]
在测试中我们还发现了两个bug.
1.string长度超过4096会越界.
2.判断大小时,负数会被强转成unsigned.
![1](https://cloud.githubusercontent.com/assets/3960661/10569118/2538ec36-7654-11e5-8f61-57980c011453.png)
![2](https://cloud.githubusercontent.com/assets/3960661/10569119/2542c9c2-7654-11e5-899c-a7245a6b365b.png)

**Comment by spin6lock** [comment]
@narsu1984 2.判断大小时,负数会被强转成unsigned. 这个没看懂，SIZEOF_LENGTH和sizeof(v)都是正数，为什么会出现负数呢？

**Comment by narsu1984** [comment]
if (size < (int)(SIZEOF_LENGTH + sizeof(v)))
如果size是负数,就会被强转成unsigned.数值很大,导致越界.
我在测试的时候遇到过,忘记怎么重现了.

**Comment by narsu1984** [comment]
@spin6lock 忘记@了 呵呵

**Comment by spin6lock** [comment]
@narsu1984 sproto.c里改size的地方比较多，如果某个地方size-=xxx导致size为负数，是有可能的，我先试试构造一个测试用例出来，再修复这个问题，谢谢~
