### ISSUE TITLE
创建SprotoRpc的时候应该传入的packagename为何值

### ISSUE THREAD

**Issue by walking-with-linght** [spin6lock/python-sproto#30]
您好，我是一个初学者，我正在用您的项目，但是遇到一些问题需要您解答一下。
我很困惑我在创建SprotoRpc的时候应该传入的packagename为何值，
![image](https://user-images.githubusercontent.com/31840262/139219151-83969958-9971-4810-b6e8-b2470013517b.png)

**Comment by spin6lock** [comment]
@Dreamforjs 你好，参考[这篇关于Sproto的Wiki](https://github.com/cloudwu/skynet/wiki/Sproto)，packagename就是指里面的主体package

**Comment by walking-with-linght** [comment]
非常感谢，我一直用skynet，却一直没关注这些，太注重逻辑上的东西了~
