### ISSUE TITLE
Ubuntu python3.10.7环境crash

### ISSUE THREAD

**Issue by firefishmoon** [spin6lock/python-sproto#36]
Ubuntu 22.04.1 LTS  python3.10.7环境， make后运行test.py 报 Segmentation fault (core dumped)。
调试发现错误可能在python_sproto.c的 decode回调函数里。

**Comment by spin6lock** [comment]
尴尬， `mysetobject(SprotoError, PyUnicode_FromFormat("unexpected type: %s", type));` 这里写错了，应该是`%d`，但是改完后测试用例有报错，我有空再看看
